# Generated by Django 3.2.7 on 2022-06-08 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(choices=[('amber', 'Amber'), 
                                                        ( 'hazel', 'Hazel'), 
                                                        ('blue', 'Blue'), 
                                                        ('green', 'Green'), 
                                                        ('brown', 'Brown'), 
                                                        ('dark-brown', 'Dark Brown')], 
                                                max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('eye_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toy.eyecolor', null=True)),
            ],
        ),
    ]
